import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  caseStudiesSidebar: [
    'case-studies/ScalingADeveloperDocsPlatform',
    'case-studies/PaysafeDeveloperCenter',
    'case-studies/DocusaurusPortfolio',
  ],

  documentationSamplesSidebar: [
    'case-studies/MDES4Merchants',
    'case-studies/PaysafeDeveloperJS',
    'case-studies/MasterpassMerchantIntegrationGuide',
    'case-studies/AMXInspiredSignageComposer',
  ],

  skillsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'skills',
    },
  ],

  toolsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tools',
    },
  ],
};

export default sidebars;
