import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
  caseStudiesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'case-studies',
    },
  ],

  skillsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'skills',
    },
  ],

    toolsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tools',
    },
  ],
};

export default sidebars;
